### ISSUE TITLE
Store access token in local storage

### ISSUE THREAD

**Issue by oliverbarnes** [participateapp/web-client#10]

**Comment by ThomasWeiser** [comment]
To use local storage in Elm you either has to wait for [elm-lang/persistent-cache](https://github.com/elm-lang/persistent-cache) or use a port.

For now I would propose to wait for a native solution.

**Comment by oliverbarnes** [comment]
Good point, let's wait for elm-lang/persistent-cache.

**Comment by ThomasWeiser** [comment]
Changed my mind: Storing the access token is useful right now. We need it for testing workflows that start with a certain route (e.g. `/porposals/:id`) without the need to login first.

So I implemented this using ports. See commits 600890c4, 692719e1 and 21dfe2b2 in PR #19.
I used sessionStorage for now, can be switched to localStorage easily.

It may still worthwhile to switch to [elm-lang/persistent-cache](https://github.com/elm-lang/persistent-cache) once it is released.

**Comment by oliverbarnes** [comment]
Thanks for already implementing this, Thomas. The only small note I'd make is, in the future this might be better submitted as a separate PR, even if just to be merged right away so it can be used on a WIP branch. Doesn't make a huge difference now, of course :)
