### ISSUE TITLE
Figure out how to color buttons differently

### ISSUE THREAD

**Issue by oliverbarnes** [participateapp/web-client#11]
Right now it inherits the primary or accent colors

http://package.elm-lang.org/packages/debois/elm-mdl/7.6.0/Material-Button

https://github.com/debois/elm-mdl/blob/7.6.0/src/Material/Button.elm#L169

**Comment by ThomasWeiser** [comment]
This seems to be handled by the following properties for the button:
- `Button.colored`: Colors according to color scheme
- `Color.background <| Color.color Color.Lime Color.S500`: Use a specific color

**Comment by oliverbarnes** [comment]
do you know how to change the button text color as well?

**Comment by ThomasWeiser** [comment]
`Color.text color`: Set text or foreground color.

http://package.elm-lang.org/packages/debois/elm-mdl/latest/Material-Color
