### ISSUE TITLE
Project details view

### ISSUE THREAD

**Issue by oliverbarnes** [participateapp/web-client#14]
```
As a participant
Once I submit a new proposal
I want to see the saved proposal
```

The API returns the saved proposal, we need to create a new route and display the proposal attributes there, no frills.

One question here is where to save the proposal, in the model. Feels weird to have a top-level `proposal` entry. And since the current participant is the author, it could make sense to have it be a record inside a `proposals` list. `model.me.proposals`

This gets me worried about keeping this synced with the API, and about how to update this when the current participant updates the proposal itself. Maybe too early to worry about this?

**Comment by oliverbarnes** [comment]
@ThomasWeiser looks like I won't have time to implement this tonight, is it cool if I assign you to it?

The main complexity I see is
- [ ] routing with an id

Not sure if it's too early to have this, but I think navigating to a proposal should be possible by shareable links, and so it'd be nice to have `/proposals/:id` links.

This adds to the question above (see issue description), on how to save proposals on app state and how to fetch them. The kind of thing that `ember-data` takes care of out-of-the-box.

**Comment by ThomasWeiser** [comment]
Working on this in #19
