### ISSUE TITLE
Proposal support count

### ISSUE THREAD

**Issue by oliverbarnes** [participateapp/web-client#35]
```
As a participant
In order to gauge how popular a proposal is
I need to see its support count
```

It should be visible on both the proposal listing and proposal details views. It should be updated on support addition and removal.

(Support count will affect proposal lists ordering in the future, something to keep in mind)

Implementation details:

Proposal data payloads from `GET /proposals`, `GET /proposals/:id` and `POST /supports` (side-loaded) now include a `support-count` attribute:

```
"id": "1",
"type": "proposal",
"attributes": {
  ...
  "support-count": 0
}
```

**Comment by tnum** [comment]
I have added the proposal count to the proposal listing and proposal detail mockup

**Comment by oliverbarnes** [comment]
This is implemented 👍
