### ISSUE TITLE
Deployment of demo

### ISSUE THREAD

**Issue by oliverbarnes** [participateapp/web-client#59]
I think we should start putting this up so we can show people, and also so @tnum can review progress.

What's the state of deployment for Elm, Thomas? Where do you think we should host the demo? Is it a matter of bundling the Phoenix api with the Elm app and put it up on Heroku, for example?

**Comment by ThomasWeiser** [comment]
As a start I would suggest to deploy the backend to Heroku and the frontend to GitHub Pages.

Reasoning:
- Heroku is an easy and nice way to deploy Elixir and Postgres.
- It would be possible to put the frontend code to Heroku too, including compilation of Elm code.
- However, the code for one Heroku app has to be pushed from one git repo, I believe.
- Currently backend and frontend are in separate repos. As the API may be used independently of the current frontend, it seems reasonable to keep the repos apart.
- Deployed frontend code is static, so any static http hosting is fine (after local compilation).

Options for later:
- Scripted synchronous deployment of both frontend and backend. May be based on GitHub tags.
- Common deployment to Heroku (or another PaaS / cloud service) by means of an extra repo that pulls in the two original repos.

@oliverbarnes thoughts?

I will start with deploying the backend in https://github.com/oliverbarnes/participate-api/issues/35

**Comment by ThomasWeiser** [comment]
Locally served frontend works with the [Heroku-deployed backend](https://github.com/oliverbarnes/participate-api/pull/35).
Just set `apiUrl ="https://participate-api.herokuapp.com"`

@oliverbarnes For further tests and for deploying the frontend, could you please:
- publish the branch `gh-pages` at GitHub Pages (in the settings of this repo), either at `https://oliverbarnes.github.io/` if possible (not sure), otherwise at `https://oliverbarnes.github.io/participate`
- whitelist these domains (or URLs ?) in the Facebook app settings:
    - https://oliverbarnes.github.io/
    - https://oliverbarnes.github.io/participate
    - http://participate.thomasweiser.de/

Thanks!

**Comment by ThomasWeiser** [comment]
Aside from Facebook authentication (see above): The test deployment at http://participate.thomasweiser.de/ seems to be working when I manually set the `accessToken` in session storage.

**Comment by oliverbarnes** [comment]
Done:

* `gh-pages` published to `https://oliverbarnes.github.io/participate/`
* Set up a new facebook app for this demo, with the above domain whitelisted and `https://oliverbarnes.github.io/participate/facebook_redirect` as the redirect url. Looks like I can only have one redirect url setup, btw. I'm sending you the app id and secret privately

**Comment by ThomasWeiser** [comment]
Thanks!

Currently the app works only in a root directory. I will change that and deploy it to `https://oliverbarnes.github.io/participate/`

**Comment by oliverbarnes** [comment]
Hmm, this makes me wonder if it's not time to switch participate to its own organization, something I've been considering doing. Besides then having a `https://participate.github.io` where the app could run in root dir, it'd also be good for its future visibility. I might do this switch this weekend

**Comment by oliverbarnes** [comment]
Ok, created the [organization](https://github.com/participateapp) but it looks like the github-pages is still published to a sub-directory, https://participateapp.github.io/web-client/, and that can't be changed as far as I can see. I'm updating the facebook app permissions

**Comment by ThomasWeiser** [comment]
Cool! Having a dedicated organization is a great step for the project.

Sure, finally the app should be deployed to a URL without sub-dirs. But I think it's no harm if the app is prepared to work also from a sub-dir URL. It's already done actually (untested though).

**Comment by ThomasWeiser** [comment]
Implemented in #62 

Demo of current version: https://participateapp.github.io/

**Comment by oliverbarnes** [comment]
Cool, this is done!
